import { IProduct } from 'app/shared/model/product.model';

export const products: IProduct[] = [
  {
    id: 1,
    title: 'Dịch vụ gỡ giới hạn 12 tháng tham gia nhóm Google',
    oldPrice: 50000,
    newPrice: 20000,
    discount: 60,
    img: '/content/images/chat-GPT-plus.webp',
  },
  {
    id: 2,
    title: 'Tăng Tim Tiktok Người Việt Thật',
    oldPrice: 22000,
    newPrice: 830000,
    discount: 65,
    img: '/content/images/chat-GPT-plus.webp',
  },
  {
    id: 3,
    title: 'Kích hoạt License Michanger Plus 1 Tháng',
    oldPrice: 300000,
    newPrice: 250000,
    discount: 17,
    img: '/content/images/chat-GPT-plus.webp',
  },
  {
    id: 4,
    title: 'Gia Hạn Canva Pro Chính Chủ (1 Tháng)',
    oldPrice: 108333,
    newPrice: 16000,
    discount: 85,
    img: '/content/images/chat-GPT-plus.webp',
  },
  {
    id: 5,
    title: 'Dịch vụ gỡ giới hạn 12 tháng tham gia nhóm Google',
    oldPrice: 50000,
    newPrice: 20000,
    discount: 60,
    img: '/content/images/chat-GPT-plus.webp',
  },
  {
    id: 6,
    title: 'Tăng Tim Tiktok Người Việt Thật',
    oldPrice: 22000,
    newPrice: 830000,
    discount: 65,
    img: '/content/images/chat-GPT-plus.webp',
  },
  {
    id: 7,
    title: 'Kích hoạt License Michanger Plus 1 Tháng',
    oldPrice: 300000,
    newPrice: 250000,
    discount: 17,
    img: '/content/images/chat-GPT-plus.webp',
  },
  {
    id: 8,
    title: 'Gia Hạn Canva Pro Chính Chủ (1 Tháng)',
    oldPrice: 108333,
    newPrice: 16000,
    discount: 85,
    img: '/content/images/chat-GPT-plus.webp',
  },
];
